# Generated by Django 2.2.4 on 2019-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
